"""Phase 3 — Isosteric heat of adsorption Q_st for CO₂/ALF.

Computes Q_st(N) via the Clausius–Clapeyron / van't Hoff relation using the
production isotherm CSV generated by phase3_production_isotherm.py.

Best-model parameters: K_eff_GPa = 0.7, eps_assoc_K = 400.

Method
------
For each target loading N (mmol/g), invert the isotherm p(N, T) by
interpolation at each temperature, then apply:

    Q_st = R * T1 * T2 / (T2 - T1) * ln(p2 / p1)   [J/mol]

Two T-pairs are used:
    Pair A: T1 = 273 K, T2 = 298 K
    Pair B: T1 = 298 K, T2 = 323 K

The reported Q_st is the average of the two estimates.

Output
------
  figures/27_phase3_qst.png   — two-panel figure
  Printed table at N = 0.5, 1.0, 2.0, 3.0 mmol/g
"""
from __future__ import annotations

import sys
from pathlib import Path

import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import numpy as np
import pandas as pd
from scipy.interpolate import interp1d

# ---------------------------------------------------------------------------
# Paths — script works both as standalone and when called from repo root
# ---------------------------------------------------------------------------
_SCRIPT = Path(__file__).resolve()
_REPO_ROOT = _SCRIPT.parents[3]
DATA_DIR = _REPO_ROOT / "applications" / "alf_co2"
RES_DIR  = DATA_DIR / "results"
FIG_DIR  = DATA_DIR / "figures"
FIG_DIR.mkdir(parents=True, exist_ok=True)

CSV_PATH = RES_DIR / "phase3_production_isotherms.csv"

# ---------------------------------------------------------------------------
# Physical constants
# ---------------------------------------------------------------------------
R = 8.314  # J mol^-1 K^-1

# Best-model selector
K_EFF  = 0.7   # GPa
EPS_A  = 400.0  # K

# Temperature pairs for Clausius-Clapeyron
T_PAIRS = [(273.0, 298.0), (298.0, 323.0)]

# Loading grid (mmol/g) — skip below 0.05 to avoid noise
N_QUERY_MIN = 0.1
N_QUERY_MAX = 4.0
N_QUERY_N   = 40
N_QUERY = np.linspace(N_QUERY_MIN, N_QUERY_MAX, N_QUERY_N)

# Evans calorimetry reference band (kJ/mol)
QST_REF_LO = 25.0
QST_REF_HI = 35.0

# ---------------------------------------------------------------------------
# Load data
# ---------------------------------------------------------------------------
def load_best_model(csv_path: Path) -> pd.DataFrame:
    df = pd.read_csv(csv_path)
    mask = (
        np.isclose(df["K_eff_GPa"], K_EFF, atol=1e-9) &
        np.isclose(df["eps_assoc_K"], EPS_A, atol=1e-9)
    )
    sub = df[mask].copy()
    if sub.empty:
        raise ValueError(
            f"No rows found for K_eff_GPa={K_EFF}, eps_assoc_K={EPS_A}.\n"
            f"Available: K_eff={sorted(df.K_eff_GPa.unique())}, "
            f"eps_assoc={sorted(df.eps_assoc_K.unique())}"
        )
    return sub


# ---------------------------------------------------------------------------
# Build p(N) interpolator for each temperature
# ---------------------------------------------------------------------------
def build_p_interpolator(df_model: pd.DataFrame, T: float) -> interp1d:
    """Return a function p_bar = f(N_mmol_g) at temperature T (K).

    The isotherm is monotone in N vs p, so we sort by N and interpolate.
    """
    sub = df_model[np.isclose(df_model["T_K"], T, atol=0.5)].copy()
    if sub.empty:
        raise ValueError(f"No isotherm data at T={T} K.")
    sub = sub.sort_values("N_mmol_g")
    N_arr = sub["N_mmol_g"].values
    p_arr = sub["p_bar"].values

    # Remove duplicate N values (keep last = highest p)
    _, idx = np.unique(N_arr, return_index=True)
    N_arr = N_arr[idx]
    p_arr = p_arr[idx]

    return interp1d(N_arr, p_arr, kind="linear", bounds_error=False,
                    fill_value=(p_arr[0], p_arr[-1]))


# ---------------------------------------------------------------------------
# Clausius-Clapeyron Q_st
# ---------------------------------------------------------------------------
def qst_pair(p_func_T1: interp1d, p_func_T2: interp1d,
             T1: float, T2: float, N_arr: np.ndarray) -> np.ndarray:
    """Q_st in J/mol for each N in N_arr."""
    p1 = p_func_T1(N_arr)
    p2 = p_func_T2(N_arr)

    # Guard: both pressures must be positive and interpolation must be valid
    ratio = np.where((p1 > 0) & (p2 > 0), p2 / p1, np.nan)
    qst = R * T1 * T2 / (T2 - T1) * np.log(ratio)  # J/mol
    return qst


# ---------------------------------------------------------------------------
# Pressure at reference temperature (298 K) for panel 2 x-axis
# ---------------------------------------------------------------------------
def get_p_at_298(df_model: pd.DataFrame, N_arr: np.ndarray) -> np.ndarray:
    p_func = build_p_interpolator(df_model, T=298.0)
    return p_func(N_arr)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main() -> None:
    print(f"Loading CSV: {CSV_PATH}")
    df_model = load_best_model(CSV_PATH)
    temps_available = sorted(df_model["T_K"].unique())
    print(f"  Temperatures in best model: {temps_available}")
    print(f"  Rows: {len(df_model)}")

    # ------------------------------------------------------------------ #
    # Build interpolators for all required temperatures                   #
    # ------------------------------------------------------------------ #
    required_temps = sorted({t for pair in T_PAIRS for t in pair})
    p_funcs: dict[float, interp1d] = {}
    for T in required_temps:
        p_funcs[T] = build_p_interpolator(df_model, T)

    # ------------------------------------------------------------------ #
    # Compute Q_st for each T-pair                                        #
    # ------------------------------------------------------------------ #
    qst_estimates: list[np.ndarray] = []
    pair_labels: list[str] = []

    for T1, T2 in T_PAIRS:
        try:
            qst_j = qst_pair(p_funcs[T1], p_funcs[T2], T1, T2, N_QUERY)
            qst_kj = qst_j / 1000.0
            qst_estimates.append(qst_kj)
            pair_labels.append(f"{int(T1)}–{int(T2)} K")
            print(f"  Q_st pair ({T1}–{T2} K): "
                  f"min={np.nanmin(qst_kj):.2f}, "
                  f"max={np.nanmax(qst_kj):.2f} kJ/mol")
        except ValueError as exc:
            print(f"  WARNING: skipping pair ({T1},{T2}): {exc}")

    if not qst_estimates:
        raise RuntimeError("No Q_st estimates could be computed.")

    qst_avg = np.nanmean(np.stack(qst_estimates, axis=0), axis=0)  # kJ/mol

    # ------------------------------------------------------------------ #
    # Pressure axis at T = 298 K                                         #
    # ------------------------------------------------------------------ #
    p_298 = get_p_at_298(df_model, N_QUERY)  # bar

    # ------------------------------------------------------------------ #
    # Print table at key loadings                                        #
    # ------------------------------------------------------------------ #
    print("\n" + "=" * 55)
    print(f"{'N (mmol/g)':>12}  {'Q_st avg (kJ/mol)':>18}  "
          + "  ".join(f"{lbl:>14}" for lbl in pair_labels))
    print("-" * 55)
    N_TABLE = [0.5, 1.0, 2.0, 3.0]
    for N_t in N_TABLE:
        # Find nearest index
        idx = np.argmin(np.abs(N_QUERY - N_t))
        row = f"{N_QUERY[idx]:>12.2f}  {qst_avg[idx]:>18.2f}"
        for est in qst_estimates:
            row += f"  {est[idx]:>14.2f}"
        print(row)
    print("=" * 55)

    # ------------------------------------------------------------------ #
    # Figure                                                             #
    # ------------------------------------------------------------------ #
    colors_pair = ["#1f77b4", "#ff7f0e"]  # blue, orange per T-pair
    color_avg   = "#2ca02c"               # green for average
    color_ref   = "#d62728"               # red shading for Evans band

    fig, axes = plt.subplots(1, 2, figsize=(12, 5))
    fig.suptitle(
        r"Isosteric Heat of Adsorption $Q_\mathrm{st}$ — CO$_2$/ALF"
        f"\n(Best model: $K_\\mathrm{{eff}}$ = {K_EFF} GPa, "
        f"$\\varepsilon_\\mathrm{{assoc}}$ = {int(EPS_A)} K)",
        fontsize=12, y=1.01
    )

    # ---- Panel 1: Q_st vs loading N ---------------------------------- #
    ax1 = axes[0]

    # Evans reference band
    ax1.axhspan(QST_REF_LO, QST_REF_HI, color=color_ref, alpha=0.15,
                label=f"Evans ref. {QST_REF_LO}–{QST_REF_HI} kJ/mol")

    # Individual T-pair estimates
    for i, (qst_kj, lbl) in enumerate(zip(qst_estimates, pair_labels)):
        ax1.plot(N_QUERY, qst_kj, "--", color=colors_pair[i], lw=1.4,
                 alpha=0.75, label=f"Pair {lbl}")

    # Average
    ax1.plot(N_QUERY, qst_avg, "-", color=color_avg, lw=2.2,
             label="Average $Q_\\mathrm{st}$")

    ax1.set_xlabel("Loading  $N$  (mmol g$^{-1}$)", fontsize=12)
    ax1.set_ylabel("$Q_\\mathrm{st}$  (kJ mol$^{-1}$)", fontsize=12)
    ax1.set_xlim(N_QUERY_MIN, N_QUERY_MAX)
    ax1.set_ylim(bottom=0)
    ax1.legend(fontsize=9, loc="upper right")
    ax1.grid(True, linestyle=":", alpha=0.5)
    ax1.xaxis.set_minor_locator(mticker.AutoMinorLocator())
    ax1.yaxis.set_minor_locator(mticker.AutoMinorLocator())

    # Annotate table points
    for N_t in N_TABLE:
        idx = np.argmin(np.abs(N_QUERY - N_t))
        ax1.axvline(N_QUERY[idx], color="grey", lw=0.7, ls=":")

    # ---- Panel 2: Q_st vs pressure at 298 K -------------------------- #
    ax2 = axes[1]

    # Evans reference band
    ax2.axhspan(QST_REF_LO, QST_REF_HI, color=color_ref, alpha=0.15,
                label=f"Evans ref. {QST_REF_LO}–{QST_REF_HI} kJ/mol")

    for i, (qst_kj, lbl) in enumerate(zip(qst_estimates, pair_labels)):
        ax2.plot(p_298, qst_kj, "--", color=colors_pair[i], lw=1.4,
                 alpha=0.75, label=f"Pair {lbl}")

    ax2.plot(p_298, qst_avg, "-", color=color_avg, lw=2.2,
             label="Average $Q_\\mathrm{st}$")

    ax2.set_xlabel("Pressure at 298 K  $p$  (bar)", fontsize=12)
    ax2.set_ylabel("$Q_\\mathrm{st}$  (kJ mol$^{-1}$)", fontsize=12)
    ax2.set_xscale("log")
    ax2.set_ylim(bottom=0)
    ax2.legend(fontsize=9, loc="upper right")
    ax2.grid(True, linestyle=":", alpha=0.5, which="both")
    ax2.yaxis.set_minor_locator(mticker.AutoMinorLocator())

    plt.tight_layout()

    out_path = FIG_DIR / "27_phase3_qst.png"
    fig.savefig(out_path, dpi=150, bbox_inches="tight")
    print(f"\nFigure saved → {out_path}")
    plt.close(fig)


if __name__ == "__main__":
    main()
